### PR TITLE
ModemConfig: Set notification channel blockable

### PR DESCRIPTION
**Pull request by dtrunk90**
`android.app.NotificationChannel#mSystemBlockable` is `false` by default.
If the app was built with system signature the notification channel cannot be blocked.

### CODE REVIEW

**Comment by dtrunk90** [comment]
@jerpelea any comments on this? can you merge it?

**Comment by MarijnS95** [comment]
> @jerpelea any comments on this? can you merge it?

Demanding a review and instant merge within 6 minutes of posting is a bit harsh isn't it? :rofl:

**Review by MarijnS95 — CHANGES_REQUESTED** [review]
This function will only be available in the next Android release:

https://developer.android.com/reference/android/app/NotificationChannel#setBlockable(boolean)

I don't think we'll want to merge this for master just yet, perhaps if an `aosp-t` branch is created.

Please also state this in the title and commit message to avoid future confusion. We usually use the `[T]` prefix to indicate the Android release version in PR titles.

**Comment by luk1337** [comment]
@MarijnS95 NotificationChannel::setBlockable(boolean) is available to apps using system-current APIs, and this is one of them.
* https://github.com/sonyxperiadev/SonyOpenTelephony/blob/master/ModemConfig/Android.bp#L14
* https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-12.1.0_r2/core/api/system-current.txt#771

**Comment by MarijnS95** [comment]
That changed since Android Q then, where it was still called `setBlockableSystem`.

**Comment by dtrunk90** [comment]
> > @jerpelea any comments on this? can you merge it?
> 
> Demanding a review and instant merge within 6 minutes of posting is a bit harsh isn't it? rofl

Sorry for that. I just wanted to make sure anyone will be notified.

The problem here is: If we add this app users aren't able to mute the notification. And it pops up after each reboot. If you try to mute them you'll see a "These notifications can't be modified" message. With the patch applied we are able to mute the notification channel completely. It's totally legit to have this notification. But we should at least give users the ability to mute them.

**Comment by MarijnS95** [comment]
> Sorry for that. I just wanted to make sure anyone will be notified.

That seems quite normal for a project maintainer?

> The problem here is: If we add this app users aren't able to mute the notification. And it pops up after each reboot. If you try to mute them you'll see a "These notifications can't be modified" message. With the patch applied we are able to mute the notification channel completely. It's totally legit to have this notification. But we should at least give users the ability to mute them.

Why don't we remove this notification altogether? We've already spent thrice the time and energy it took to puzzle together the insanity that is modem files and their XML gobbledygook on the necessity of this notification, and it's tiring.

As far as I remember it doesn't even work on newer models, and some older models have already been "deprecated" from the project.

**Comment by jerpelea** [comment]
The app is not needed for 2021 devices,but there several devices that benefit from it

**Pull request merged**
